version: "3.9"
services:
  api:
    build: ./api
    container_name: api
    ports:
      - "5001:5000"
    networks:
      - proyecto1
  web:
    build: ./web
    container_name: front
    ports:
      - "5173:5173"
    networks:
      - proyecto1
  
networks:
  proyecto1:
    driver: bridge  
  