name: Upload to Docker Hub
on:
  push:
    branches:
      - Proyecto1_docker-compose

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        run: |
          docker-compose -f docker-compose.yml build api
          docker tag codigo_facilito_proyecto_1-api:latest atrombetta81/codigo_facilito_proyecto1_api:latest
          docker push atrombetta81/codigo_facilito_proyecto1_api:latest

      - name: Build and push Web image
        run: |
          docker-compose -f docker-compose.yml build web --tag codigo_facilito_proyecto_1-web:latest
          docker push atrombetta81/codigo_facilito_proyecto1_web:latest
